### PR TITLE
use prefix for additional subscriptions and further issues

### PR DESCRIPTION
**Pull request by PLCHome**
**solved: prefix for subscribing topics is added to additional subscriptions #35**

A new switch has been installed which specifies whether the prefix is ​​used for additional subscriptions.
If the switch is activated, all statuses of the MQTT Client namespaces are processed without a prefix.
If the switch is set, the system behaves as before.

Further issues:

- If a status was added by an additional subscription, the value was missing. This is now initially added as text.
- When changing the topic of a subscripted status, the old topic was not removed from the subscriptions.
- When deleting a subscripted status, the old topic was not removed from the subscriptions.
- If the prefix was changed in the config, the topic was also subscribed with the old prefix.
- If an additional subscription receives a value for a non-subscripted value, the value of the status has been changed.
- Unsubscribe did not work with a prefix.

### CODE REVIEW

**Comment by PLCHome** [comment]
@Pmant @GermanBluefox @Apollon77 @aurodionov @algar42
Can we discuss the pull request?

**Comment by Apollon77** [comment]
Honestly I have no clue about mqtt, so I can not say anything about ot beside "syntactical correctness"

**Comment by PLCHome** [comment]
@Pmant 
Can we discuss the pull request?

**Comment by PLCHome** [comment]
@Pmant @aurodionov @algar42
Can we discuss the pull request?

**Comment by Apollon77** [comment]
@Pmant could you ave a look please?

**Comment by PLCHome** [comment]
Can we discuss the pull request?

**Comment by PLCHome** [comment]
I can close it if that's better.

**Comment by Apollon77** [comment]
@Pmant @GermanBluefox please have a look!

**Comment by PLCHome** [comment]
@Pmant
Next month: can we discuss the pull request?

**Comment by PLCHome** [comment]
Yes, you won, it's your project, it doesn't need any new features. And see for yourself that you are fixing the errors. A year without an answer, fuck off you could have written me at least once.

**Pull request closed without merging**
