### PR TITLE
fix for js-controller 2.0

### PR DESCRIPTION
**Pull request by algar42**
Fix subscription to defined topics on adapter start.

### CODE REVIEW

**Comment by GermanBluefox** [comment]
It is no more required, because of https://github.com/Pmant/ioBroker.mqtt-client/pull/19

**Comment by algar42** [comment]
#19 still does not work, unfortunately. 
1.  MQTT version 3.0.0 does not connect to mosquitto 1.6 (latest). It states connected but does not receive any topics. Adapted should works fine with MQTT 2.18.0
2. Problem with adapter restart still not resolved in this merge.

**Comment by GermanBluefox** [comment]
I can start and connect adapter. Which errors do you have?

**Comment by algar42** [comment]
Error 1: 
Adapter stops right after install:
image
but then killed again:
image
(it is exactly the same error that was in previous code of adapter)
...try to push restart couple of times and you will see.

Error 3: 
Current version does not subscribes to topics.. 
had a quick look at code: 
 a) in onConnect, subscribe function called with topics object as first arg:
image
but the fuction itselfs expects adapter as first arg:
image
(but even if adapter added to the call, it still does not return callback at _client.subscribe... )

Error 4 (probably):  
image
Is it correct to have 'includes(id)' here? Isn't it returns true/false and not position?  maybe indexOf? 

That's all a can say now. Probably there are other problems in code after it was completely rewritten, but, sorry, have no time to get deeper today. 
 
@GermanBluefox , as you said in your message above - we can start and connect adapter... and that's all it can't do now... No topics received.. and restart is still borken. :)

**Pull request closed without merging**
